/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as AppTagsRouteImport } from './routes/_app/tags'
import { Route as AppSourcesRouteImport } from './routes/_app/sources'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppEntriesNewRouteImport } from './routes/_app/entries/new'
import { Route as AppEntriesIdRouteImport } from './routes/_app/entries/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesNewRoute = AppEntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesIdRoute = AppEntriesIdRouteImport.update({
  id: '/entries/$id',
  path: '/entries/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/inbox': typeof AppInboxRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/library': typeof AppLibraryRoute
  '/profile': typeof AppProfileRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/sources': typeof AppSourcesRoute
  '/tags': typeof AppTagsRoute
  '/share/$token': typeof ShareTokenRoute
  '/entries/$id': typeof AppEntriesIdRoute
  '/entries/new': typeof AppEntriesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/inbox': typeof AppInboxRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/library': typeof AppLibraryRoute
  '/profile': typeof AppProfileRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/sources': typeof AppSourcesRoute
  '/tags': typeof AppTagsRoute
  '/share/$token': typeof ShareTokenRoute
  '/entries/$id': typeof AppEntriesIdRoute
  '/entries/new': typeof AppEntriesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/tags': typeof AppTagsRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/entries/$id': typeof AppEntriesIdRoute
  '/_app/entries/new': typeof AppEntriesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/activity'
    | '/inbox'
    | '/knowledge'
    | '/library'
    | '/profile'
    | '/review'
    | '/search'
    | '/sources'
    | '/tags'
    | '/share/$token'
    | '/entries/$id'
    | '/entries/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/activity'
    | '/inbox'
    | '/knowledge'
    | '/library'
    | '/profile'
    | '/review'
    | '/search'
    | '/sources'
    | '/tags'
    | '/share/$token'
    | '/entries/$id'
    | '/entries/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/activity'
    | '/_app/inbox'
    | '/_app/knowledge'
    | '/_app/library'
    | '/_app/profile'
    | '/_app/review'
    | '/_app/search'
    | '/_app/sources'
    | '/_app/tags'
    | '/share/$token'
    | '/_app/entries/$id'
    | '/_app/entries/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/new': {
      id: '/_app/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof AppEntriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/$id': {
      id: '/_app/entries/$id'
      path: '/entries/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof AppEntriesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppInboxRoute: typeof AppInboxRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppTagsRoute: typeof AppTagsRoute
  AppEntriesIdRoute: typeof AppEntriesIdRoute
  AppEntriesNewRoute: typeof AppEntriesNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppInboxRoute: AppInboxRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppProfileRoute: AppProfileRoute,
  AppReviewRoute: AppReviewRoute,
  AppSearchRoute: AppSearchRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppTagsRoute: AppTagsRoute,
  AppEntriesIdRoute: AppEntriesIdRoute,
  AppEntriesNewRoute: AppEntriesNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
