// NOTE: This file should be regenerated by running Metro (`pnpm dev:native`).
// Stub declarations are provided below for IDE support when node_modules is unavailable.

// Pull in Uniwind's `className` type augmentations for react-native components.
// Without this, `className` is only typed where Expo's react-native-web types
// load (macOS), so type-checking passes locally but fails on Linux/CI. It lands
// on ViewProps/TextProps, so it also covers react-native-reanimated's Animated.*.
/// <reference types="uniwind/types" />

declare module "uniwind" {
  export interface UniwindConfig {
    themes: readonly ["light", "dark"]
  }

  export const Uniwind: {
    setTheme(theme: string): void
    readonly currentTheme: string
    readonly hasAdaptiveThemes: boolean
    updateInsets(insets: {
      top: number
      bottom: number
      left: number
      right: number
    }): void
    updateCSSVariables(
      theme: string,
      variables: Record<string, string | number>
    ): void
    getCSSVariable(name: string): string | number | undefined
    getCSSVariable(names: string[]): (string | number | undefined)[]
  }

  export function useUniwind(): {
    theme: string
    hasAdaptiveThemes: boolean
  }

  export function useResolveClassNames(
    className: string
  ): Record<string, unknown>

  export function useCSSVariable(name: string): string | number | undefined
  export function useCSSVariable(
    names: string[]
  ): (string | number | undefined)[]

  export function withUniwind<T>(
    component: T,
    mapping?: Record<string, { fromClassName: string; styleProperty: string }>
  ): T

  export function ScopedTheme(props: {
    theme: string
    children: React.ReactNode
  }): React.ReactNode
}

declare module "uniwind/metro" {
  export function withUniwindConfig(
    config: any,
    options: {
      cssEntryFile: string
      polyfills?: { rem?: number }
      extraThemes?: string[]
      dtsFile?: string
      debug?: boolean
      isTV?: boolean
      experimental?: { defaultStyles?: boolean }
    }
  ): any
}

declare module "uniwind/diagnostics" {
  export function enableDiagnostics(options: {
    reportMounts?: boolean
    reportUnmounts?: boolean
    reportUpdates?: boolean
  }): void
}
